version: "3.5"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/test
      - ./docker/nginx/test.conf:/etc/nginx/conf.d/test.conf
    depends_on:
      - php
    networks:
      - test

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/test
    networks:
      - test

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    networks:
      - test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_HOSTS: mysql
    depends_on:
      - mysql
    networks:
      - test

  memcached:
    image: memcached:1.6-alpine
    networks:
      - test

  redis:
    image: redis:5-alpine
    networks:
      - test

networks:
  test:
